spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bossdd_monitor?serverTimezone=GMT%2B8
    username: root
    password: root

honoka:
  qqrobot:
    admin-qq: 123456
    developing-group: 123456
    framework:
      # 指定一个机器人框架的实现
      impl: onebot
      onebot:
        host: localhost
        websocket-port: 3001
        http-port: 3101

app:
  bossdd:
    city-code: 101010100
    search-word: java
  browser:
    user-data-dir:
      path: ./build/selenium/user-data

logging:
  level:
    de.honoka.bossddmonitor.mapper: debug