spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bossdd_monitor?serverTimezone=GMT%2B8
    username: root
    password: root

honoka:
  qqrobot:
    # 指定一个机器人框架的实现
    framework: onebot
    admin-qq: 123456
    developing-group: 123456
    onebot:
      host: localhost
      websocket-port: 3001
      http-port: 3101

logging:
  level:
    de.honoka.bossddmonitor.mapper: debug