spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bossdd_monitor?serverTimezone=GMT%2B8
    username: root
    password: root

honoka:
  qqrobot:
    admin-qq: 12345
    developing-group: 10000
    framework:
      # 指定一个机器人框架的实现
      impl: onebot
      onebot:
        host: localhost
        websocket-port: 3001
        http-port: 3101

app:
  browser:
    user-data-dir:
      path: ./build/selenium/user-data
  data-service:
    monitor-task:
      initial-delay: 0s
      delay: 1m

logging:
  level:
    de.honoka.bossddmonitor.mapper: debug