[versions]
# project modules version
root = "1.0.0-dev"

# dependencies version
kotlin = "1.8.10"
kotlin-coroutines = "1.6.4"
spring-boot = "3.2.5"
qqrobot-spring-boot-starter = "2.0.1-dev"
selenium = "4.27.0"
lombok = "1.18.26"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
dependency-management = "io.spring.dependency-management:1.1.6"
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
selenium-bom = { module = "org.seleniumhq.selenium:selenium-dependencies-bom", version.ref = "selenium" }
qqrobot-spring-boot-starter = { module = "de.honoka.qqrobot:qqrobot-spring-boot-starter", version.ref = "qqrobot-spring-boot-starter" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
